apiVersion: v1
kind: Service
metadata:
  name: teamflow-backend-service
  labels:
    app: teamflow
    component: backend
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
      protocol: TCP
  selector:
    app: teamflow
    component: backend
